### ISSUE TITLE
Ask for Helps

### ISSUE THREAD

**Issue by StartMvoe** [pongthang/generative-AI-anomaly-detection#1]
Excuse me! When I run the file "generate_classifier_free_guaidance_bone_condition", something wrong was happend in the section of CrossAttention, Specifically, the different dimensions of “x” with torch.Size([64, 196, 256]) and “context” with torch.Size([64, 1, 1, 64]) result in the inability to run the “batch_stize later, seq_len, dim = x.shape“ in the “reshaped_heads_to_match-dim”. 
Perhaps the update of the GenerativeModels project (https://github.com/Project-MONAI/GenerativeModels) 2 months ago caused this error to occur. Could you please offer your all generative files to me(p21201071@stu.ahu.edu.cn) ? Sincerely!

**Comment by StartMvoe** [comment]
I have solved it. Thank you for your kind project! Sincerely!

**Comment by pongthang** [comment]
> I have solved it. Thank you for your kind project! Sincerely!
Great , Welcome ... Hope you enjoy the project.
